kind: Service
apiVersion: v1
metadata:
  name: "akkahttpplayground-service"
spec:
  selector:
    app: "akkahttpplayground-app"
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
  type: NodePort
#    nodePort: 30000