apiVersion: v1
kind: Pod
metadata:
  name: "akkahttpplaygroundname"
  namespace: "default"
spec:
  containers:
    - name: "akkahttpplayground"
      image: "localhost:5000/akkahttp-playground:0.0.1"
      imagePullPolicy: "Always"
      ports:
        - containerPort: 8181
      #resources:
      #  cpu: "1"
      #  memory: "50"
  imagePullSecrets:
    - name: myregistrykey